Repository V0ldek/GameBoard, pull requests merged in 2019-04, with the labels that each got.

#26 Feature/azure db connection
  .dockerignore
  DataLayer/Configuration.cs
  DataLayer/Context/GameBoardDbContext.Model.cs
  DataLayer/DataLayer.csproj
  DataLayer/Migrations/20190323142538_CreateIdentitySchema.Designer.cs
  DataLayer/Migrations/20190323142538_CreateIdentitySchema.cs
  DataLayer/Migrations/GameBoardDbContextModelSnapshot.cs
  GameBoard/Connected Services/Application Insights/ConnectedService.json
  GameBoard/Dockerfile
  GameBoard/GameBoard.csproj
  GameBoard/Program.cs
  GameBoard/Properties/PublishProfiles/GameBoardDevelopFree - Web Deploy.pubxml
  GameBoard/Properties/launchSettings.json
  GameBoard/Startup.cs
  GameBoard/Views/Shared/_Layout.cshtml
  GameBoard/appsettings.json
Labels: sprint 1

#31 Fixed a NRE bug in GetFriendsRequestAsync.
  DataLayer/Migrations/Scripts/20190414094415_AddedApplicationUserAndFriendship_Up.sql
  LogicLayer/Friends/FriendsService.cs
Labels: bug, sprint 1

#33 Fixed the resending a previously rejected friend request bug
  DataLayer/Migrations/Scripts/20190414094415_AddedApplicationUserAndFriendship_Up.sql
Labels: sprint 2
