Repository V0ldek/GameBoard, pull requests merged in 2019-05, with the labels that each got.

#29 Feature/mail notifications
  DataLayer/Context/GameBoardDbContext.cs
  DataLayer/Entities/ApplicationUser.cs
  DataLayer/Repositories/IGameBoardRepository.cs
  GameBoard.sln
  GameBoard/Areas/Identity/Pages/Account/ConfirmEmailInfo.cshtml
  GameBoard/Areas/Identity/Pages/Account/ConfirmEmailInfo.cshtml.cs
  GameBoard/Areas/Identity/Pages/Account/ConfirmedEmail.cshtml
  GameBoard/Areas/Identity/Pages/Account/ConfirmedEmail.cshtml.cs
  GameBoard/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
  GameBoard/Areas/Identity/Pages/Account/Login.cshtml
  GameBoard/Areas/Identity/Pages/Account/Login.cshtml.cs
  GameBoard/Areas/Identity/Pages/Account/Manage/Index.cshtml
  GameBoard/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
  GameBoard/Areas/Identity/Pages/Account/Register.cshtml
  GameBoard/Areas/Identity/Pages/Account/Register.cshtml.cs
  GameBoard/Areas/Identity/Pages/Account/ResetPassword.cshtml
  GameBoard/Areas/Identity/Pages/Account/ResetPassword.cshtml.cs
  GameBoard/Areas/Identity/Pages/Error.cshtml
  GameBoard/Areas/Identity/Pages/Error.cshtml.cs
  GameBoard/Controllers/ControllerExtensions.cs
  GameBoard/Controllers/FriendsController.cs
  GameBoard/Errors/Error.cs
  GameBoard/Errors/ErrorHandlingWrapper.cs
  GameBoard/Errors/IErrorHandlingWrapper.cs
  GameBoard/GameBoard.csproj
  GameBoard/Scripts/Popovers/popoverGenerator.ts
  GameBoard/Scripts/tsconfig.json
  GameBoard/Startup.cs
  GameBoard/appsettings.Development.json
  GameBoard/appsettings.json
  GameBoard/package-lock.json
  GameBoard/package.json
  LogicLayer/Configurations/MailNotificationsConfiguration.cs
  LogicLayer/Friends/Dtos/FriendRequestExtension.cs
  LogicLayer/Friends/Dtos/FriendshipExtension.cs
  LogicLayer/Friends/Dtos/FriendshipStatusExtension.cs
  LogicLayer/Friends/FriendsService.cs
  LogicLayer/LogicLayer.csproj
  LogicLayer/Notifications/Html/Inlined/email-confirmation.html
  LogicLayer/Notifications/Html/Inlined/event-cancellation.html
  LogicLayer/Notifications/Html/Inlined/event-invitation.html
  LogicLayer/Notifications/Html/Inlined/friend-invitation.html
  LogicLayer/Notifications/Html/Inlined/password-reset.html
  LogicLayer/Notifications/Html/Raw/email-confirmation.html
  LogicLayer/Notifications/Html/Raw/event-cancellation.html
  LogicLayer/Notifications/Html/Raw/event-invitation.html
  LogicLayer/Notifications/Html/Raw/friend-invitation.html
  LogicLayer/Notifications/Html/Raw/password-reset.html
  LogicLayer/Notifications/Html/Raw/styles.css
  LogicLayer/Notifications/IMailSender.cs
  LogicLayer/Notifications/MailSender.cs
  LogicLayer/Notifications/Notification.cs
  LogicLayer/Properties/launchSettings.json
  LogicLayer/UserSearch/Dtos/ApplicationUserExtension.cs
  LogicLayer/UserSearch/IUserSearchService.cs
  LogicLayer/UserSearch/UserSearchService.cs
  Tools/CssInliner/CssInliner.cs
  Tools/CssInliner/CssInliner.csproj
  Tools/CssInliner/Properties/launchSettings.json
  Tools/CssInliner/readme.txt
Labels: sprint 1, sprint 2

#35 Feature/exiting an event
  DataLayer/Context/GameBoardDbContext.Model.cs
  DataLayer/Enums/ParticipationStatus.cs
  DataLayer/Migrations/20190506181129_ExitingAnEvent.Designer.cs
  DataLayer/Migrations/20190506181129_ExitingAnEvent.cs
  GameBoard/Areas/Identity/Pages/Account/ConfirmedEmail.cshtml.cs
  GameBoard/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
  GameBoard/Areas/Identity/Pages/Account/Login.cshtml
  GameBoard/Areas/Identity/Pages/Account/Register.cshtml.cs
  GameBoard/Controllers/FriendsController.cs
  GameBoard/Controllers/GameEventController.cs
  GameBoard/Controllers/GameEventParticipationController.cs
  GameBoard/Errors/ErrorHandlingWrapper.cs
  GameBoard/Models/GameEvent/ExitGameEventViewModel.cs
  GameBoard/Models/GameEvent/GameEventDtoExtensions.cs
  GameBoard/Scripts/tsconfig.json
  GameBoard/Views/Friends/FriendRequest.cshtml
  GameBoard/Views/GameEvent/GameEvent.cshtml
  GameBoard/Views/GameEventParticipation/ExitGameEvent.cshtml
  GameBoard/Views/Home/Index.cshtml
  GameBoard/Views/Shared/Components/Error/ErrorViewComponent.cs
  GameBoard/Views/Shared/Components/GameEventInviteForm/GameEventInviteForm.cshtml
  GameBoard/Views/Shared/Components/GameEventsList/GameEventsList.cshtml
  GameBoard/Views/Shared/Components/UserSearchResults/UserSearchResults.cshtml
  GameBoard/wwwroot/css/gameEvent.css
  LogicLayer/Configuration.cs
  LogicLayer/Friends/Dtos/SendFriendRequestDto.cs
  LogicLayer/Friends/Exceptions/FriendRequestAlreadyFinalizedException.cs
  LogicLayer/Friends/Exceptions/FriendRequestException.cs
  LogicLayer/Friends/Exceptions/InvitingYourselfException.cs
  LogicLayer/Friends/FriendsService.cs
  LogicLayer/Friends/IFriendsService.cs
  LogicLayer/GameEventInvites/GameEventInviteService.cs
  LogicLayer/GameEventInvites/IGameEventInviteService.cs
  LogicLayer/GameEventParticipations/Dtos/SendGameEventInvitationDto.cs
  LogicLayer/GameEventParticipations/Exceptions/GameEventParticipationException.cs
  LogicLayer/GameEventParticipations/GameEventParticipationService.cs
  LogicLayer/GameEventParticipations/IGameEventParticipationService.cs
  LogicLayer/GameEvents/GameEventService.cs
  LogicLayer/LogicLayer.csproj
  LogicLayer/Notifications/Html/Inlined/event-cancellation.html
  LogicLayer/Notifications/Html/Raw/event-cancellation.html
  LogicLayer/Notifications/IMailSender.cs
  LogicLayer/Notifications/MailSender.cs
Labels: sprint 2

#46 Release/v1.1.0
  GameBoard/GameBoard.csproj
Labels: release, sprint 3

#48 Added a hacky keep-alive mechanism to cron job services.
  GameBoard/HostedServices/CronScheduledService.cs
  GameBoard/HostedServices/EventReminders/DayBeforeGameEventReminderCronScheduledService.cs
  GameBoard/HostedServices/KeepAlive/HttpRequestKeepAlive.cs
  GameBoard/HostedServices/KeepAlive/IKeepAlive.cs
  GameBoard/HostedServices/ScopedHostedService.cs
  GameBoard/Startup.cs
Labels: Final stretch, bug

#50 Release/v1.2.0
  .gitignore
  DataLayer/Migrations/Scripts/20190520094439_DescriptionTab_Up.sql
  GameBoard/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml
  GameBoard/GameBoard.csproj
  GameBoard/Views/Shared/Components/FriendsSidebar/FriendsSidebar.cshtml
  GameBoard/Views/Shared/Components/GroupCard/GroupCard.cshtml
  GameBoard/Views/Shared/_Layout.cshtml
  GameBoard/wwwroot/css/groupAddBox.css
  LogicLayer/Groups/GroupsService.cs
  README.md
Labels: final stretch, release

#53 Hotfix/send game invitate button layout
  GameBoard/HostedServices/HostedService.cs
  GameBoard/HostedServices/KeepAlive/HttpRequestKeepAlive.cs
  GameBoard/Views/Shared/Components/FriendsSidebar/FriendsSidebar.cshtml
  GameBoard/Views/Shared/_Layout.cshtml
  GameBoard/wwwroot/css/descriptionTab.css
  GameBoard/wwwroot/css/gameEvent.css
  GameBoard/wwwroot/css/groupCard.css
Labels: final stretch, release

#54 Hotfix/send game invitate button layout
  GameBoard/HostedServices/HostedService.cs
  GameBoard/HostedServices/KeepAlive/HttpRequestKeepAlive.cs
  GameBoard/Views/Shared/Components/FriendsSidebar/FriendsSidebar.cshtml
  GameBoard/Views/Shared/_Layout.cshtml
  GameBoard/wwwroot/css/descriptionTab.css
  GameBoard/wwwroot/css/gameEvent.css
  GameBoard/wwwroot/css/groupCard.css
Labels: final stretch, hotfix
